# Generated by Django 4.0.1 on 2022-01-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0002_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='region',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, related_name='region', to='frexco.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='a', max_length=40, primary_key=True, serialize=False),
        ),
    ]
