# Generated by Django 4.0.1 on 2022-01-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0003_fruit_region_alter_region_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='region',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
