# Generated by Django 4.0.1 on 2022-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0005_alter_fruit_name_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
    ]
